version: "3"

set: [errexit, nounset, pipefail, xtrace]

includes:
  ext:
    taskfile: ./ext/Taskfile.yml
    dir: ./ext

  rust:
    taskfile: ./rust/Taskfile.yml
    dir: ./rust

tasks:
  ext-full:
    cmds:
      - task: rust:ext-copy
      - task: ext:build
