# fly.toml app configuration file generated for ethg-ist on 2023-11-17T20:09:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ethg-ist"
primary_region = "otp"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
