version: "3"

set: [errexit, nounset, pipefail, xtrace]

includes:
  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client
  proxy:
    taskfile: ./proxy/Taskfile.yml
    dir: ./proxy
  source:
    taskfile: ./source/Taskfile.yml
    dir: ./source
  verifier:
    taskfile: ./verifier/Taskfile.yml
    dir: ./verifier
  docker:
    taskfile: ./Taskfile.docker.yml
    dir: .

tasks:
  check:
    deps:
      - client:check
      - proxy:check
      - source:check
      - verifier:check

  build-dev:
    deps:
      - client:build-dev
      - proxy:build-dev
      - source:build-dev
      - verifier:build-dev

  build-release:
    deps:
      - client:build-release
      - proxy:build-release
      - source:build-release
      - verifier:build-release

  ext-copy:
    cmds:
      - task: source:copy-release
      - task: client:copy-release
